"""test-feat/user branch

Revision ID: 4124031a104d
Revises: 2525031a5653
Create Date: 2025-12-01 19:06:55.362921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4124031a104d'
down_revision: Union[str, Sequence[str], None] = '2525031a5653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_health_conditions_user_id_key'), 'user_health_conditions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_health_conditions_user_id_key'), 'user_health_conditions', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
